"""Khoi tao CSDL

Revision ID: 389f7c77cec5
Revises: 
Create Date: 2025-11-06 11:03:35.955929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389f7c77cec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calam',
    sa.Column('maca', sa.Integer(), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('giobatdau', sa.Time(), nullable=False),
    sa.Column('gioketthuc', sa.Time(), nullable=False),
    sa.Column('hesoluong', sa.Integer(), nullable=True),
    sa.Column('sogio', sa.Numeric(precision=10, scale=2), server_default=sa.FetchedValue(), nullable=True),
    sa.PrimaryKeyConstraint('maca')
    )
    op.create_table('chucvu',
    sa.Column('macv', sa.Integer(), nullable=False),
    sa.Column('tencv', sa.String(length=100), nullable=False),
    sa.Column('dongiagio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('macv')
    )
    op.create_table('dichvu',
    sa.Column('madv', sa.Integer(), nullable=False),
    sa.Column('tendv', sa.String(length=100), nullable=False),
    sa.Column('gia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('thoiluong', sa.Integer(), nullable=True),
    sa.Column('donvitinh', sa.String(length=50), nullable=True),
    sa.Column('anhdichvu', sa.LargeBinary(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('mota', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('madv')
    )
    op.create_table('khachhang',
    sa.Column('makh', sa.Integer(), nullable=False),
    sa.Column('hoten', sa.String(length=100), nullable=False),
    sa.Column('sdt', sa.String(length=20), nullable=True),
    sa.Column('diachi', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('taikhoan', sa.String(length=50), nullable=False),
    sa.Column('matkhau', sa.String(length=255), nullable=False),
    sa.Column('anhdaidien', sa.String(length=255), nullable=True),
    sa.Column('ngaytao', sa.DateTime(), nullable=True),
    sa.Column('trangthai', sa.String(length=20), nullable=True),
    sa.Column('resettoken', sa.String(length=255), nullable=True),
    sa.Column('resettokenexpire', sa.DateTime(), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=True, comment='Lưu mã OTP gửi đến email'),
    sa.Column('otp_expire', sa.DateTime(), nullable=True, comment='Lưu thời điểm hết hạn của mã OTP'),
    sa.PrimaryKeyConstraint('makh'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('taikhoan')
    )
    op.create_table('lichhen',
    sa.Column('malh', sa.Integer(), nullable=False),
    sa.Column('ngaygio', sa.DateTime(), nullable=False),
    sa.Column('trangthai', sa.String(length=50), nullable=True),
    sa.Column('makh', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['makh'], ['khachhang.makh'], ),
    sa.PrimaryKeyConstraint('malh')
    )
    op.create_table('nhanvien',
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('hoten', sa.String(length=100), nullable=False),
    sa.Column('sdt', sa.String(length=20), nullable=True),
    sa.Column('diachi', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('taikhoan', sa.String(length=50), nullable=False),
    sa.Column('matkhau', sa.String(length=255), nullable=False),
    sa.Column('anhnhanvien', sa.String(length=255), nullable=True),
    sa.Column('macv', sa.Integer(), nullable=False),
    sa.Column('ngaytao', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('trangthai', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['macv'], ['chucvu.macv'], ),
    sa.PrimaryKeyConstraint('manv'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('taikhoan')
    )
    op.create_table('chitietlichhen',
    sa.Column('malh', sa.Integer(), nullable=False),
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('madv', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['madv'], ['dichvu.madv'], ),
    sa.ForeignKeyConstraint(['malh'], ['lichhen.malh'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('malh', 'manv', 'madv')
    )
    op.create_table('dangkyschicht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('maca', sa.Integer(), nullable=False),
    sa.Column('ngaydangky', sa.DateTime(), nullable=True),
    sa.Column('trangthai', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['maca'], ['calam.maca'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hoadon',
    sa.Column('mahd', sa.Integer(), nullable=False),
    sa.Column('ngaylap', sa.DateTime(), nullable=True),
    sa.Column('tongtien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('makh', sa.Integer(), nullable=False),
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('trangthai', sa.String(length=50), nullable=True),
    sa.Column('malh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['makh'], ['khachhang.makh'], ),
    sa.ForeignKeyConstraint(['malh'], ['lichhen.malh'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('mahd'),
    sa.UniqueConstraint('malh')
    )
    op.create_table('hoithoai',
    sa.Column('maht', sa.Integer(), nullable=False),
    sa.Column('ngaybatdau', sa.DateTime(), nullable=True),
    sa.Column('makh', sa.Integer(), nullable=True),
    sa.Column('manv', sa.Integer(), nullable=True),
    sa.Column('tin_nhan_cuoi_noi_dung', sa.Text(), nullable=True),
    sa.Column('tin_nhan_cuoi_thoi_gian', sa.DateTime(), nullable=True),
    sa.Column('tin_nhan_cuoi_la_khach_gui', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['makh'], ['khachhang.makh'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('maht')
    )
    op.create_table('luong',
    sa.Column('maluong', sa.Integer(), nullable=False),
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('luongcoban', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('thuong', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('khautru', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tongluong', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('maluong')
    )
    op.create_table('nhanvien_calam',
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('maca', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maca'], ['calam.maca'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('manv', 'maca')
    )
    op.create_table('chitiethoadon',
    sa.Column('macthd', sa.Integer(), nullable=False),
    sa.Column('mahd', sa.Integer(), nullable=False),
    sa.Column('madv', sa.Integer(), nullable=False),
    sa.Column('soluong', sa.Integer(), nullable=True),
    sa.Column('dongia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('thanhtien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['madv'], ['dichvu.madv'], ),
    sa.ForeignKeyConstraint(['mahd'], ['hoadon.mahd'], ),
    sa.PrimaryKeyConstraint('macthd')
    )
    op.create_table('thanhtoan',
    sa.Column('matt', sa.Integer(), nullable=False),
    sa.Column('mahd', sa.Integer(), nullable=False),
    sa.Column('sotien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phuongthuc', sa.String(length=50), nullable=True),
    sa.Column('ngaythanhtoan', sa.DateTime(), nullable=True),
    sa.Column('ghichu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mahd'], ['hoadon.mahd'], ),
    sa.PrimaryKeyConstraint('matt')
    )
    op.create_table('tinnhan',
    sa.Column('matn', sa.Integer(), nullable=False),
    sa.Column('noidung', sa.Text(), nullable=False),
    sa.Column('thoigiangui', sa.DateTime(), nullable=True),
    sa.Column('maht', sa.Integer(), nullable=False),
    sa.Column('nguoigui_makh', sa.Integer(), nullable=True),
    sa.Column('nguoigui_manv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maht'], ['hoithoai.maht'], ),
    sa.ForeignKeyConstraint(['nguoigui_makh'], ['khachhang.makh'], ),
    sa.ForeignKeyConstraint(['nguoigui_manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('matn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tinnhan')
    op.drop_table('thanhtoan')
    op.drop_table('chitiethoadon')
    op.drop_table('nhanvien_calam')
    op.drop_table('luong')
    op.drop_table('hoithoai')
    op.drop_table('hoadon')
    op.drop_table('dangkyschicht')
    op.drop_table('chitietlichhen')
    op.drop_table('nhanvien')
    op.drop_table('lichhen')
    op.drop_table('khachhang')
    op.drop_table('dichvu')
    op.drop_table('chucvu')
    op.drop_table('calam')
    # ### end Alembic commands ###
