"""empty message

Revision ID: 3b6a5108b5a3
Revises: f8937c064e64
Create Date: 2025-11-14 08:50:32.426982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6a5108b5a3'
down_revision = 'f8937c064e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangluongchitiet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manv', sa.Integer(), nullable=False),
    sa.Column('maca', sa.Integer(), nullable=False),
    sa.Column('maluong_thang', sa.Integer(), nullable=True),
    sa.Column('ngay_lam', sa.Date(), nullable=False),
    sa.Column('sogio_lam', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dongia_gio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('luong_ca', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['maca'], ['calam.maca'], ),
    sa.ForeignKeyConstraint(['maluong_thang'], ['luong.maluong'], ),
    sa.ForeignKeyConstraint(['manv'], ['nhanvien.manv'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maca')
    )
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bangluongchitiet_maluong_thang'), ['maluong_thang'], unique=False)
        batch_op.create_index(batch_op.f('ix_bangluongchitiet_manv'), ['manv'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bangluongchitiet_manv'))
        batch_op.drop_index(batch_op.f('ix_bangluongchitiet_maluong_thang'))

    op.drop_table('bangluongchitiet')
    # ### end Alembic commands ###
