"""Add daily bonus/deduction to BangLuongChiTiet

Revision ID: 41e6313d2fd5
Revises: 813bebe40926
Create Date: 2025-11-14 11:21:41.142154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e6313d2fd5'
down_revision = '813bebe40926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thuong_ca', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('khautru_ca', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.drop_column('khautru_ca')
        batch_op.drop_column('thuong_ca')

    # ### end Alembic commands ###
