"""Add daily bonus/deduction to BangLuongChiTiet

Revision ID: 64bc6b55d74c
Revises: 41e6313d2fd5
Create Date: 2025-11-14 14:17:01.444383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bc6b55d74c'
down_revision = '41e6313d2fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lichhen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manv', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nhanvien', ['manv'], ['manv'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lichhen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manv')

    # ### end Alembic commands ###
