"""Fix unique constraint on BangLuongChiTiet

Revision ID: 813bebe40926
Revises: 3b6a5108b5a3
Create Date: 2025-11-14 10:14:54.527889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813bebe40926'
down_revision = '3b6a5108b5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bangluongchitiet_maca_key'), type_='unique')
        batch_op.create_unique_constraint('_manv_maca_uc', ['manv', 'maca'])
        batch_op.create_index(batch_op.f('ix_bangluongchitiet_maca'), ['maca'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bangluongchitiet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bangluongchitiet_maca'))
        batch_op.drop_constraint('_manv_maca_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('bangluongchitiet_maca_key'), ['maca'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
