"""empty message

Revision ID: b809b57ea821
Revises: 64bc6b55d74c
Create Date: 2025-11-14 14:51:30.616369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b809b57ea821'
down_revision = '64bc6b55d74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoadon', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hoadon_manv_fkey'), type_='foreignkey')
        batch_op.drop_column('manv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoadon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manv', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('hoadon_manv_fkey'), 'nhanvien', ['manv'], ['manv'])

    # ### end Alembic commands ###
