"""Fix relations for LichHen, ChiTietLichHen, and HoaDon

Revision ID: f3b12dbde06b
Revises: b809b57ea821
Create Date: 2025-11-14 14:55:56.936188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b12dbde06b'
down_revision = 'b809b57ea821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chitietlichhen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chitietlichhen_manv_fkey'), type_='foreignkey')
        batch_op.drop_column('manv')

    with op.batch_alter_table('hoadon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manv', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'nhanvien', ['manv'], ['manv'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoadon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manv')

    with op.batch_alter_table('chitietlichhen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manv', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('chitietlichhen_manv_fkey'), 'nhanvien', ['manv'], ['manv'])

    # ### end Alembic commands ###
