"""Add da_doc to TinNhan

Revision ID: f8937c064e64
Revises: 389f7c77cec5
Create Date: 2025-11-13 15:48:12.009837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8937c064e64'
down_revision = '389f7c77cec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tinnhan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('da_doc', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tinnhan', schema=None) as batch_op:
        batch_op.drop_column('da_doc')

    # ### end Alembic commands ###
